FROM python:3.7-slim

ENV PYTHONPATH "${PYTHONPATH}:/usr/local/lib/python3.7/site-packages:/app"

RUN pip install --upgrade pip
RUN pip install --no-cache-dir numpy scipy pandas matplotlib

RUN mkdir /app
WORKDIR /app
